### ISSUE TITLE
MerchantKit debugging tips

### ISSUE THREAD

**Issue by kutakmir** [benjaminmayo/merchantkit#14]
Hi Ben, firstly many thanks for building this library it looks very good!

I am trying to debug the purchase of a renewable subscription and I did not receive any callback from the:

         let task = merchant.commitPurchaseTask(for: purchase)
         task.onCompletion = { result in
             switch result {
             case .succeeded(_):
                 print("purchase completed")
             case .failed(let error):
                 print("\(error)")
             }
         }

         task.start()

piece of code.

What do you suggest as a to-do list if I want to debug this?

**Comment by benjaminmayo** [comment]
Firstly, try turning on `canGenerateLogs` on the `Merchant`. This will enable some debug messages that the framework itself produces (note: log coverage is not complete yet.). Please try enabling that and seeing if any weird errors show up in the console. If not, I'm happy to pursue this to see where the bug lies.

**Comment by kutakmir** [comment]
For some reason, I don't see any logs...

I am `Using MerchantKit (0.8.1)`

This is the class:

[SubscriptionServiceManager.swift.zip](https://github.com/benjaminmayo/merchantkit/files/2484509/SubscriptionServiceManager.swift.zip)
I tried just with the Merchant and also with ProductInterfaceController.

**Comment by benjaminmayo** [comment]
Are you registering the products with the Merchant, and calling the `Merchant.setup()` method at application launch? I can't see that in your file.

**Comment by kutakmir** [comment]
Good point, I'll do that.

**Comment by benjaminmayo** [comment]
What I would recommend is writing a `prepare()` method on the `SubscriptionServiceManager`. Inside this method, register the array of products and call `setup()` on the merchant. Call the `prepare()` method from the app delegate `application(_:didFinishLaunchingWithOptions:)`.

**Comment by kutakmir** [comment]
ok, I did that and now I am getting a nice little:
`Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo={NSLocalizedDescription=Cannot connect to iTunes Store}`

So finally an error, that's great!

**Comment by benjaminmayo** [comment]
That StoreKit error generally means you are using the simulator when the simulator does not support that operation, or you aren't using the correct iTunes Store credentials. IIRC automatically renewing subscriptions must be tested on device.

By the way, if you are using this singleton pattern, I would not use a `ProductInterfaceController`. Just make the tasks from the `Merchant` and call them from within your methods. You can get updates through the completion handlers of the tasks and/or the `merchant(_, didChangeStatesFor:)` delegate.

**Comment by benjaminmayo** [comment]
Please close this issue if your problem is resolved. Eventually, I will have fully-fledged documentation (and sample code project) that will incorporate this kind of information.

I also want to add better error reporting when clients forget to register products, or call `setup()`. As aforementioned, logging (guarded by `canGenerateLogs`) is sparse in the codebase at the moment.

**Comment by kutakmir** [comment]
It works like a charm, thanks a lot Ben, you are a star!
