### ISSUE TITLE
Purchase.subscriptionTerms returns non-nil for non-subscription products

### ISSUE THREAD

**Issue by ekurutepe** [benjaminmayo/merchantkit#22]
The documentation says that this property should be nil if the product is not a subscription. Which makes total sense. 

In release 0.10.0, it does return non-nil even for non-subscriptions. 

I tried setting a breakpoint in the property getter in `Purchase.swift` but somehow it was not hit.

I'll investigate further.

**Comment by benjaminmayo** [comment]
I believe this is fixed on master, as [per the code changes here](
https://github.com/benjaminmayo/merchantkit/commit/3cc4f00585e5f7c3bbf26b826668506520309605#diff-955ad7d95e0397e23487b9f623c10252). I noticed that StoreKIt started returning values like ‘0 days’ for duration, rather than leaving the underlying property as `nil`.

I’m looking to do a 0.11 release soon that will incorporate this change.

**Comment by ekurutepe** [comment]
awesome! This sounds like a StoreKit bug then since the docs there say it's supposed to return nil as well. Cheers.

**Comment by ekurutepe** [comment]
I can confirm that `master` works as expected.
