### ISSUE TITLE
know if a free trial is in progress or has expired?

### ISSUE THREAD

**Issue by ghost** [benjaminmayo/merchantkit#32]
How can I tell if a free trial / introductory trial for 7 days is never used, currently being used or has expired? I can't seem to understand...

**Comment by benjaminmayo** [comment]
This is currently not possible.

**Comment by ghost** [comment]
Seems like a rather important feature though -- do you have a possible ETA? I'd hate to go back to StoreKit directly :-(

**Comment by Kirow** [comment]
Not possible out of box, but you can implement your own `ReceiptValidator`. In general same as `ServerReceiptValidator`, but different response parser and extended `Receipt` model (for ex.: `FullReceipt: Receipt`). Then you need to store it inside validator or add callback (because merchant.latestFetchedReceipt is internal) to read all json values outside framework. Not elegant, but possible. See [docs](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html#//apple_ref/doc/uid/TP40010573-CH106-SW1) in case you will try it this way.

**Comment by benjaminmayo** [comment]
You don't have to 'go back to StoreKit directly' wholesale, you can use `MerchantKit` for everything else and then just validate a receipt independently to get the free trial info out. Obviously, this is something I would like to support in the framework (eg. the `introductoryOffer` property should return `nil` when it has already been used up.)

**Comment by ghost** [comment]
Hi Benjamin, any eta for this feature? I really would appreciate it.

**Comment by benjaminmayo** [comment]
The local receipt does not document free trial status, so implementation of this is a bit blocked ATM.

**Comment by xinatanil** [comment]
Any ETA on the feature?
