### ISSUE TITLE
Localized Title on Purchase

### ISSUE THREAD

**Issue by Chris-BMA** [benjaminmayo/merchantkit#9]
I have added a localizedTitle computed property on the Purchase struct, in order to get at the title of the IAP since it is tucked into the internal skProduct.  I didn't see any other way to get at that name.  Am I doing this right?  If so, are you taking PR's on this repo?

**Comment by benjaminmayo** [comment]
Hi Chris,

The (undocumented) MerchantKit recommendation is to get at that information from external means; i.e. info like presentable titles should be retrieved based on the `Product.productIdentifier` object alone. This is because you almost always will want to display the product in a storefront list before the available purchases have been fetched. 

That being said, I am not opposed to adding these properties to `Purchase` directly. Happy to accept a PR for this; please implement `localizedDescription` as well as `localizedTitle`. I would also prefer these to be exposed as non-optional strings, where the empty string represents a not used value, to match the rest of the `MerchantKit` framework. How does that sound?

**Comment by Chris-BMA** [comment]
Yes a storefront list is what I'm presenting.  The only localizedTitle property that I know of is in the SKProduct, which is not accessible in Product (but it is in the Purchases returned from availablePurchasesTask).  What external means do you suggest?  I can use StoreKit API, but I'd much rather stay inside of MerchantKit.

**Comment by benjaminmayo** [comment]
Well, in my apps, I just have all the presentation metadata shipped in the bundle as a localized resource. You could use your own server infrastructure if you wanted to do something more dynamically.

**Comment by Chris-BMA** [comment]
Ok gotcha.  Yeah I'm using the localization feature built right into iTunes Connect.  That way I don't have to update a bundle file, and get the correct localized string from the SKProduct that Apple's backend gives me.  I will submit a PR in a bit for the Product change.  Thanks for the help!

**Comment by benjaminmayo** [comment]
Cheers. BTW, if you haven't seen it already, try using `ProductInterfaceController` for your storefront interface. This wraps a lot of the behaviour you'll need. If it doesn't work for your use case, I'd love to know why.

**Comment by Chris-BMA** [comment]
Yes, I'm using it and so far so good (minus the access to localizedTitle data).
